"""Rev 20: LaTeX tables generated from the result files (no hand-typed numbers).
Output: manuscript/generated/tables.tex (Tables 1-5) and manuscript/generated/tables_si.tex (Supplementary Tables S1-S4)."""
import pandas as pd, numpy as np, sys
from core import load, B
R = f'{B}/results/'; L = f'{B}/manuscript/generated/'
f0 = lambda v, n=2: f'{v:.{n}f}'
pc = lambda v, n=0: f'{100 * v:.{n}f}\\%'
d = load(None); A = d[d.in_panel_A]; AL = d[d.in_panel_A_long]
T3 = pd.read_csv(R + 'T3_core.csv').set_index('indicator'); R3 = pd.read_csv(R + 'R3_models_regime.csv').set_index('indicator')
M1 = pd.read_csv(R + 'M1_reconciliation.csv'); F1 = pd.read_csv(R + 'F1_ceiling_states.csv')
H = pd.read_csv(R + 'H1_heaping_state.csv', index_col=0)
nceil = int(F1[F1.ceiling_state == True].shape[0])
ncoord = int(A.lat.notna().sum())
t1 = [('Annual CPCB reports', '9 (2016-2024)'), ('Station-year rows extracted', '11,157'),
      ('Raw station codes / harmonized stations', '1,840 / 1,891 (54 under more than one code)'),
      ('Code series mixing more than one location', '100 of 1,840'),
      ('Stations reported per year', f"{A.groupby('Year').size().min():,} (2016) to {A.groupby('Year').size().max():,} (2024)"),
      ('Panel A / A\\_long / C (stations; station-years)', f"{A.station_uid.nunique():,}; {len(A):,} / {AL.station_uid.nunique():,}; {len(AL):,} / 467; 4,203"),
      ('Values excluded by quality control', '155'),
      ('BOD maxima at exactly 3.0 mg/L', pc(H.loc['ALL', 'BOD_eq_3'], 1)),
      ('States where FC cannot exceed 2,500 (FC censored)', f'{nceil}'),
      ('Located stations (main spatial sample)', '1,187 (1,155)'),
      ('Station-years with coordinates (Panel A)', f'{ncoord:,} ({100 * ncoord / len(A):.0f}\\%)'),
      ('Monthly records linked, 2020-2021', f"{int(M1.loc[M1.item.str.startswith('stations among'), 'value'].iat[0])} stations, {int(M1.loc[M1.item.str.startswith('linked station-years also'), 'value'].iat[0])} station-years ({int(M1.loc[M1.item.str.startswith('stations in the CPCB table in both'), 'value'].iat[0])} in both years)")]
out = ['% generated by r20/13_tables.py', '\\begin{table}[width=.9\\linewidth,cols=2,pos=h]', '\\caption{Dataset and monitoring network.}\\label{tbl:dataset}',
       '\\begin{tabular*}{\\tblwidth}{@{} p{0.43\\linewidth} p{0.41\\linewidth} @{}}', '\\toprule', 'Item & Value \\\\', '\\midrule']
out += [f'{a} & {b} \\\\' for a, b in t1] + ['\\bottomrule', '\\end{tabular*}', '\\end{table}', '']
# Table 2 thresholds
out += [r'''\begin{table*}[width=\textwidth,cols=5,pos=h]
\caption{Threshold framework (values checked against the official texts).}\label{tbl:thresholds}
\begin{tabular*}{\tblwidth}{@{} p{0.09\textwidth} p{0.15\textwidth} p{0.2\textwidth} p{0.33\textwidth} p{0.14\textwidth} @{}}
\toprule
Indicator & Statistic & Adverse if & Source & Role \\
\midrule
DO & annual minimum & $<$ 5 mg/L (BDL adverse) & Bathing criteria, E(P) Rules \citep{moef2000}; CPCB table headers & primary \\
BOD & annual maximum & $>$ 3 mg/L & same & primary \\
pH & minimum and maximum & $<$ 6.5 or $>$ 8.5 & same & primary; secondary in interpretation \\
FC & annual maximum & $>$ 2,500 MPN/100 mL; censored in 11 states and at exactly 1,600 & same (maximum permissible) & primary \\
TC & annual maximum & $>$ 5,000 MPN/100 mL & Designated best use, class C \citep{cpcbcriteria} & secondary \\
Conductivity & annual maximum & $>$ 2,250 \textmu mho/cm & Designated best use, class E & secondary \\
Nitrate & annual maximum & pooled 90th percentile & no surface-water criterion & secondary \\
DO, BOD, FC & as above & pooled 80th / 90th percentile & empirical & sensitivity \\
\bottomrule
\end{tabular*}
\end{table*}
''']
# Table 3 persistence
icc = {'FC': '$>$ 0.9', 'BOD': f0(R3.loc['ADV_BOD', 'ICC_M1']), 'DO': f0(R3.loc['ADV_DO', 'ICC_M1']), 'pH': f0(R3.loc['ADV_PH', 'ICC_M1']), '>=2 of 4': '--'}
names = {'FC': 'FC', 'BOD': 'BOD', 'DO': 'DO', 'pH': 'pH', '>=2 of 4': '$\\ge$ 2 of 4'}
out += [r'''\begin{table*}[width=\textwidth,cols=11,pos=h]
\caption{Persistence metrics and null models (Panel A\_long; FC censored; criteria in Table~\ref{tbl:thresholds}). N1, N1s, N2: mean \Pstay{} under each null. Share beyond state = (observed $-$ N1s)/(observed $-$ N1). Persistent: adverse in at least 60\% of observed years with a run of at least three, stations with four or more observed years.}\label{tbl:persistence}
\begin{tabular*}{\tblwidth}{@{} p{0.07\textwidth} p{0.045\textwidth} p{0.15\textwidth} p{0.085\textwidth} p{0.04\textwidth} p{0.04\textwidth} p{0.04\textwidth} p{0.04\textwidth} p{0.06\textwidth} p{0.05\textwidth} p{0.05\textwidth} p{0.06\textwidth} @{}}
\toprule
Indicator & Prev. & \Pstay{} (95\% CI, station) & 95\% CI, state & \Pentry & N1 & N1s & N2 & Beyond state & Jaccard, next year & ICC & Persistent \\
\midrule''']
for k in ['FC', 'BOD', 'DO', 'pH', '>=2 of 4']:
    r = T3.loc[k]
    out.append(f"{names[k]} & {f0(r.prevalence)} & {f0(r.P11)} ({r.CI_station.replace('0.', '.').replace('-.', '-.')}) & {r.CI_state} & {f0(r.P01)} & {f0(r.N1)} & {f0(r.N1s)} & {f0(r.N2)} & {pc(r.share_beyond_state)} & {f0(r.jaccard1_mean)} & {icc[k]} & {pc(r.persistent)} \\\\")
out += ['\\bottomrule', '\\end{tabular*}', '\\end{table*}', '']
# fix CI formatting: two decimals
import re
def ci2(s): a, b = s.split('-'); return f'{float(a):.2f}-{float(b):.2f}'
out = [re.sub(r'\(([0-9.]+-[0-9.]+)\)', lambda m: '(' + ci2(m.group(1).replace('-.', '-0.') if m.group(1).startswith('.') is False else '0' + m.group(1)) + ')', l) if l.startswith(tuple(names.values())) else l for l in out]
out = [re.sub(r' & (0\.[0-9]{3}-0\.[0-9]{3}) & ', lambda m: ' & ' + ci2(m.group(1)) + ' & ', l) for l in out]
# Table 4 reliability
E2 = pd.read_csv(R + 'E2_error_benchmark.csv'); M6 = pd.read_csv(R + 'M6_null_flips.csv'); M2 = pd.read_csv(R + 'M2_counts.csv')
M5 = pd.read_csv(R + 'M5_subsampling.csv'); M7 = pd.read_csv(R + 'M7_persistence_4samples.csv').set_index('indicator'); R5 = pd.read_csv(R + 'R5_fixed_effort.csv').set_index('indicator')
def e(ind, s): return E2[(E2.indicator == ind) & (E2.scenario == s)].iloc[0]
def m6(ind, v): return M6[(M6.indicator == ind) & (M6.variant.str.startswith(v))].iloc[0]
def m5(ind): return M5[(M5.indicator == ind) & (M5.samples_used == '4')].iloc[0]
row = lambda lab, cells: f'{lab} & ' + ' & '.join(cells) + ' \\\\'
out += [r'''\begin{table*}[width=\textwidth,cols=4,pos=h]
\caption{Reliability of single-year exceedance status: analytical error, sampling variability and sampling effort. Error-only expectation: status changes if each pair of consecutive years kept its level and only analytical error acted (range over error models). Monthly subset: stations in the CPCB table in both 2020 and 2021 with at least four monthly samples per year. FC censored.}\label{tbl:noise}
\begin{tabular*}{\tblwidth}{@{} p{0.4\textwidth} p{0.17\textwidth} p{0.17\textwidth} p{0.17\textwidth} @{}}
\toprule
Measure & BOD & FC & pH \\
\midrule''']
cells = []
for ind in ['BOD', 'FC (censored)', 'pH']:
    lo, mn, hi = e(ind, 'low'), e(ind, 'main'), e(ind, 'high')
    cells.append((f"{int(mn.observed_changes):,}", f"{mn.expected_changes_error_only:,.0f} ({lo.expected_changes_error_only:,.0f}-{hi.expected_changes_error_only:,.0f})",
                  f"{100 * mn.repeat_measurement_changes_station_years:.1f}\\% ({100 * lo.repeat_measurement_changes_station_years:.1f}-{100 * hi.repeat_measurement_changes_station_years:.1f})"))
out.append(row('Status changes, all stations', [c[0] for c in cells]))
out.append(row('Expected from analytical error alone (range)', [c[1] for c in cells]))
out.append(row('Station-years changed by a repeat analysis (range)', [c[2] for c in cells]))
for v, lab in [('main', 'Monthly subset, 2020-2021: observed / expected changes (95\\% range), stations'),
               ('COVID', 'June-December only'), ('two records', 'Two records in a month averaged')]:
    cs = []
    for ind in ['BOD', 'FC', 'PH']:
        r = m6(ind, v); cs.append(f"{int(r.observed_changes)} / {r.pooled_expected:.1f} ({r.pooled_lo:.0f}-{r.pooled_hi:.0f}), {int(r.stations)}")
    out.append(row(lab, cs))
nb = M2.n_BOD[M2.n_BOD > 0]
out.append(row('BOD samples per station-year, median (IQR)', [f'{nb.median():.0f} ({nb.quantile(.25):.0f}-{nb.quantile(.75):.0f})', '', '']))
out.append(row('Adverse station-years missed with 4 samples instead of all', [pc(m5(k).missed_given_adverse) for k in ['BOD', 'FC', 'PH']]))
out.append(row('\\Pstay{} 2020-2021, all samples / 4 samples', [f"{M7.loc[k, 'P11_all']:.2f} / {M7.loc[k, 'P11_4']:.2f}" for k in ['BOD', 'FC', 'PH']]))
out.append(row('Between-station ICC, all samples / one per quarter', [f"{R5.loc[k, 'ICC_all']:.2f} / {R5.loc[k, 'ICC_quarterly_median']:.2f}" for k in ['BOD', 'FC', 'PH']]))
out += ['\\bottomrule', '\\end{tabular*}', '\\end{table*}', '']
# Table 5 TCI
I1 = pd.read_csv(R + 'I1_tci_out_of_sample.csv'); I2 = pd.read_csv(R + 'I2_tci_prediction.csv').set_index('indicator'); I3 = pd.read_csv(R + 'I3_listing_churn.csv').set_index('indicator')
out += [r'''\begin{table*}[width=\textwidth,cols=6,pos=h]
\caption{Out-of-sample performance of the three-class, multi-year indicator (TCI). Classes from 2016-2020 (stations with at least three observed years); outcomes are single-year statuses in 2021-2024 (stations with at least two later years). Turnover: entries plus exits per listed station per year, 2018-2024, for the single-year list and for a rolling list of stations reliably adverse over the last three years.}\label{tbl:tci}
\begin{tabular*}{\tblwidth}{@{} p{0.27\textwidth} p{0.13\textwidth} p{0.13\textwidth} p{0.13\textwidth} p{0.13\textwidth} @{}}
\toprule
 & BOD & FC & DO & pH \\
\midrule''']
order = ['BOD', 'FC', 'DO', 'PH']
for cl in ['reliably adverse', 'borderline', 'reliably compliant']:
    g = I1[I1.class_2016_2020 == cl].set_index('indicator')
    g['share_of_classified'] = g.stations / I1.groupby('indicator').stations.sum().reindex(g.index)
    out.append(row(f'{cl.capitalize()}: share of stations / adverse share later / same class later',
                   [f"{pc(g.loc[k, 'share_of_classified'])} / {pc(g.loc[k, 'adverse_share_2021_2024'])} / {pc(g.loc[k, 'same_class_2021_2024'])}" for k in order]))
out.append(row('Stations classified', [f"{int(I1[I1.indicator == k].stations.sum()):,}" for k in order]))
out.append(row('Accuracy for 2021-2024: 2020 status, all stations', [pc(I2.loc[k, 'accuracy_single_year_2020']) for k in order]))
out.append(row('Accuracy: TCI, stations classed reliable (share)', [f"{pc(I2.loc[k, 'accuracy_tci_reliable'])} ({pc(I2.loc[k, 'tci_reliable_station_share'])})" for k in order]))
out.append(row('Accuracy: 2020 status, borderline stations', [pc(I2.loc[k, 'accuracy_single_year_on_borderline']) for k in order]))
out.append(row('Share of later status changes at borderline stations', [pc(I2.loc[k, 'share_late_changes_at_borderline']) for k in order]))
out.append(row('List turnover: single-year / TCI', [f"{I3.loc[k, 'single_year_turnover']:.2f} / {I3.loc[k, 'tci_turnover']:.2f}" for k in order]))
out += ['\\bottomrule', '\\end{tabular*}', '\\end{table*}', '', '\\input{table_context.tex}', '']
open(L + 'tables.tex', 'w').write(re.sub(r'(?<=[ {])p\{', r'>{\\raggedright\\arraybackslash}p{', '\n'.join(out)))  # ragged-right text columns
print('\n'.join(out)[:6000])
